/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as UserRouteImport } from './routes/user'
import { Route as UpvotedRouteImport } from './routes/upvoted'
import { Route as ThreadsRouteImport } from './routes/threads'
import { Route as SubmittedRouteImport } from './routes/submitted'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as ShowRouteImport } from './routes/show'
import { Route as PastRouteImport } from './routes/past'
import { Route as NewestRouteImport } from './routes/newest'
import { Route as Market_searchRouteImport } from './routes/market_search'
import { Route as MarketRouteImport } from './routes/market'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as FormatdocRouteImport } from './routes/formatdoc'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DukigenRouteImport } from './routes/dukigen'
import { Route as DaoRouteImport } from './routes/dao'
import { Route as CommentsRouteImport } from './routes/comments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RpcSplatRouteImport } from './routes/rpc/$'
import { Route as PostIdRouteImport } from './routes/post.$id'
import { Route as DukigenAgentIdRouteImport } from './routes/dukigen.$agentId'
import { Route as ApiSyncEventsRouteImport } from './routes/api/sync-events'
import { Route as ApiSeedRouteImport } from './routes/api/seed'
import { Route as ApiNotifyTxsRouteImport } from './routes/api/notify-txs'
import { Route as ApiUsersCheckNameRouteImport } from './routes/api/users/check-name'
import { Route as ApiDebugSyncEventsRouteImport } from './routes/api/debug/sync-events'
import { Route as ApiAuthRefreshRouteImport } from './routes/api/auth/refresh'
import { Route as ApiAuthNonceRouteImport } from './routes/api/auth/nonce'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthDebugLoginSplatRouteImport } from './routes/api/auth/debug-login/$'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const UpvotedRoute = UpvotedRouteImport.update({
  id: '/upvoted',
  path: '/upvoted',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsRoute = ThreadsRouteImport.update({
  id: '/threads',
  path: '/threads',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmittedRoute = SubmittedRouteImport.update({
  id: '/submitted',
  path: '/submitted',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowRoute = ShowRouteImport.update({
  id: '/show',
  path: '/show',
  getParentRoute: () => rootRouteImport,
} as any)
const PastRoute = PastRouteImport.update({
  id: '/past',
  path: '/past',
  getParentRoute: () => rootRouteImport,
} as any)
const NewestRoute = NewestRouteImport.update({
  id: '/newest',
  path: '/newest',
  getParentRoute: () => rootRouteImport,
} as any)
const Market_searchRoute = Market_searchRouteImport.update({
  id: '/market_search',
  path: '/market_search',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const FormatdocRoute = FormatdocRouteImport.update({
  id: '/formatdoc',
  path: '/formatdoc',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DukigenRoute = DukigenRouteImport.update({
  id: '/dukigen',
  path: '/dukigen',
  getParentRoute: () => rootRouteImport,
} as any)
const DaoRoute = DaoRouteImport.update({
  id: '/dao',
  path: '/dao',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentsRoute = CommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RpcSplatRoute = RpcSplatRouteImport.update({
  id: '/rpc/$',
  path: '/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PostIdRoute = PostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DukigenAgentIdRoute = DukigenAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => DukigenRoute,
} as any)
const ApiSyncEventsRoute = ApiSyncEventsRouteImport.update({
  id: '/api/sync-events',
  path: '/api/sync-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeedRoute = ApiSeedRouteImport.update({
  id: '/api/seed',
  path: '/api/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotifyTxsRoute = ApiNotifyTxsRouteImport.update({
  id: '/api/notify-txs',
  path: '/api/notify-txs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersCheckNameRoute = ApiUsersCheckNameRouteImport.update({
  id: '/api/users/check-name',
  path: '/api/users/check-name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugSyncEventsRoute = ApiDebugSyncEventsRouteImport.update({
  id: '/api/debug/sync-events',
  path: '/api/debug/sync-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRefreshRoute = ApiAuthRefreshRouteImport.update({
  id: '/api/auth/refresh',
  path: '/api/auth/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthNonceRoute = ApiAuthNonceRouteImport.update({
  id: '/api/auth/nonce',
  path: '/api/auth/nonce',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDebugLoginSplatRoute = ApiAuthDebugLoginSplatRouteImport.update({
  id: '/api/auth/debug-login/$',
  path: '/api/auth/debug-login/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comments': typeof CommentsRoute
  '/dao': typeof DaoRoute
  '/dukigen': typeof DukigenRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/formatdoc': typeof FormatdocRoute
  '/jobs': typeof JobsRoute
  '/market': typeof MarketRoute
  '/market_search': typeof Market_searchRoute
  '/newest': typeof NewestRoute
  '/past': typeof PastRoute
  '/show': typeof ShowRoute
  '/submit': typeof SubmitRoute
  '/submitted': typeof SubmittedRoute
  '/threads': typeof ThreadsRoute
  '/upvoted': typeof UpvotedRoute
  '/user': typeof UserRoute
  '/voice': typeof VoiceRoute
  '/welcome': typeof WelcomeRoute
  '/api/notify-txs': typeof ApiNotifyTxsRoute
  '/api/seed': typeof ApiSeedRoute
  '/api/sync-events': typeof ApiSyncEventsRoute
  '/dukigen/$agentId': typeof DukigenAgentIdRoute
  '/post/$id': typeof PostIdRoute
  '/rpc/$': typeof RpcSplatRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/nonce': typeof ApiAuthNonceRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
  '/api/debug/sync-events': typeof ApiDebugSyncEventsRoute
  '/api/users/check-name': typeof ApiUsersCheckNameRoute
  '/api/auth/debug-login/$': typeof ApiAuthDebugLoginSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comments': typeof CommentsRoute
  '/dao': typeof DaoRoute
  '/dukigen': typeof DukigenRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/formatdoc': typeof FormatdocRoute
  '/jobs': typeof JobsRoute
  '/market': typeof MarketRoute
  '/market_search': typeof Market_searchRoute
  '/newest': typeof NewestRoute
  '/past': typeof PastRoute
  '/show': typeof ShowRoute
  '/submit': typeof SubmitRoute
  '/submitted': typeof SubmittedRoute
  '/threads': typeof ThreadsRoute
  '/upvoted': typeof UpvotedRoute
  '/user': typeof UserRoute
  '/voice': typeof VoiceRoute
  '/welcome': typeof WelcomeRoute
  '/api/notify-txs': typeof ApiNotifyTxsRoute
  '/api/seed': typeof ApiSeedRoute
  '/api/sync-events': typeof ApiSyncEventsRoute
  '/dukigen/$agentId': typeof DukigenAgentIdRoute
  '/post/$id': typeof PostIdRoute
  '/rpc/$': typeof RpcSplatRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/nonce': typeof ApiAuthNonceRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
  '/api/debug/sync-events': typeof ApiDebugSyncEventsRoute
  '/api/users/check-name': typeof ApiUsersCheckNameRoute
  '/api/auth/debug-login/$': typeof ApiAuthDebugLoginSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comments': typeof CommentsRoute
  '/dao': typeof DaoRoute
  '/dukigen': typeof DukigenRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/formatdoc': typeof FormatdocRoute
  '/jobs': typeof JobsRoute
  '/market': typeof MarketRoute
  '/market_search': typeof Market_searchRoute
  '/newest': typeof NewestRoute
  '/past': typeof PastRoute
  '/show': typeof ShowRoute
  '/submit': typeof SubmitRoute
  '/submitted': typeof SubmittedRoute
  '/threads': typeof ThreadsRoute
  '/upvoted': typeof UpvotedRoute
  '/user': typeof UserRoute
  '/voice': typeof VoiceRoute
  '/welcome': typeof WelcomeRoute
  '/api/notify-txs': typeof ApiNotifyTxsRoute
  '/api/seed': typeof ApiSeedRoute
  '/api/sync-events': typeof ApiSyncEventsRoute
  '/dukigen/$agentId': typeof DukigenAgentIdRoute
  '/post/$id': typeof PostIdRoute
  '/rpc/$': typeof RpcSplatRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/nonce': typeof ApiAuthNonceRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
  '/api/debug/sync-events': typeof ApiDebugSyncEventsRoute
  '/api/users/check-name': typeof ApiUsersCheckNameRoute
  '/api/auth/debug-login/$': typeof ApiAuthDebugLoginSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/comments'
    | '/dao'
    | '/dukigen'
    | '/favorites'
    | '/formatdoc'
    | '/jobs'
    | '/market'
    | '/market_search'
    | '/newest'
    | '/past'
    | '/show'
    | '/submit'
    | '/submitted'
    | '/threads'
    | '/upvoted'
    | '/user'
    | '/voice'
    | '/welcome'
    | '/api/notify-txs'
    | '/api/seed'
    | '/api/sync-events'
    | '/dukigen/$agentId'
    | '/post/$id'
    | '/rpc/$'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/nonce'
    | '/api/auth/refresh'
    | '/api/debug/sync-events'
    | '/api/users/check-name'
    | '/api/auth/debug-login/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/comments'
    | '/dao'
    | '/dukigen'
    | '/favorites'
    | '/formatdoc'
    | '/jobs'
    | '/market'
    | '/market_search'
    | '/newest'
    | '/past'
    | '/show'
    | '/submit'
    | '/submitted'
    | '/threads'
    | '/upvoted'
    | '/user'
    | '/voice'
    | '/welcome'
    | '/api/notify-txs'
    | '/api/seed'
    | '/api/sync-events'
    | '/dukigen/$agentId'
    | '/post/$id'
    | '/rpc/$'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/nonce'
    | '/api/auth/refresh'
    | '/api/debug/sync-events'
    | '/api/users/check-name'
    | '/api/auth/debug-login/$'
  id:
    | '__root__'
    | '/'
    | '/comments'
    | '/dao'
    | '/dukigen'
    | '/favorites'
    | '/formatdoc'
    | '/jobs'
    | '/market'
    | '/market_search'
    | '/newest'
    | '/past'
    | '/show'
    | '/submit'
    | '/submitted'
    | '/threads'
    | '/upvoted'
    | '/user'
    | '/voice'
    | '/welcome'
    | '/api/notify-txs'
    | '/api/seed'
    | '/api/sync-events'
    | '/dukigen/$agentId'
    | '/post/$id'
    | '/rpc/$'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/nonce'
    | '/api/auth/refresh'
    | '/api/debug/sync-events'
    | '/api/users/check-name'
    | '/api/auth/debug-login/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommentsRoute: typeof CommentsRoute
  DaoRoute: typeof DaoRoute
  DukigenRoute: typeof DukigenRouteWithChildren
  FavoritesRoute: typeof FavoritesRoute
  FormatdocRoute: typeof FormatdocRoute
  JobsRoute: typeof JobsRoute
  MarketRoute: typeof MarketRoute
  Market_searchRoute: typeof Market_searchRoute
  NewestRoute: typeof NewestRoute
  PastRoute: typeof PastRoute
  ShowRoute: typeof ShowRoute
  SubmitRoute: typeof SubmitRoute
  SubmittedRoute: typeof SubmittedRoute
  ThreadsRoute: typeof ThreadsRoute
  UpvotedRoute: typeof UpvotedRoute
  UserRoute: typeof UserRoute
  VoiceRoute: typeof VoiceRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiNotifyTxsRoute: typeof ApiNotifyTxsRoute
  ApiSeedRoute: typeof ApiSeedRoute
  ApiSyncEventsRoute: typeof ApiSyncEventsRoute
  PostIdRoute: typeof PostIdRoute
  RpcSplatRoute: typeof RpcSplatRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthNonceRoute: typeof ApiAuthNonceRoute
  ApiAuthRefreshRoute: typeof ApiAuthRefreshRoute
  ApiDebugSyncEventsRoute: typeof ApiDebugSyncEventsRoute
  ApiUsersCheckNameRoute: typeof ApiUsersCheckNameRoute
  ApiAuthDebugLoginSplatRoute: typeof ApiAuthDebugLoginSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upvoted': {
      id: '/upvoted'
      path: '/upvoted'
      fullPath: '/upvoted'
      preLoaderRoute: typeof UpvotedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads': {
      id: '/threads'
      path: '/threads'
      fullPath: '/threads'
      preLoaderRoute: typeof ThreadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submitted': {
      id: '/submitted'
      path: '/submitted'
      fullPath: '/submitted'
      preLoaderRoute: typeof SubmittedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/show': {
      id: '/show'
      path: '/show'
      fullPath: '/show'
      preLoaderRoute: typeof ShowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/past': {
      id: '/past'
      path: '/past'
      fullPath: '/past'
      preLoaderRoute: typeof PastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newest': {
      id: '/newest'
      path: '/newest'
      fullPath: '/newest'
      preLoaderRoute: typeof NewestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market_search': {
      id: '/market_search'
      path: '/market_search'
      fullPath: '/market_search'
      preLoaderRoute: typeof Market_searchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formatdoc': {
      id: '/formatdoc'
      path: '/formatdoc'
      fullPath: '/formatdoc'
      preLoaderRoute: typeof FormatdocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dukigen': {
      id: '/dukigen'
      path: '/dukigen'
      fullPath: '/dukigen'
      preLoaderRoute: typeof DukigenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dao': {
      id: '/dao'
      path: '/dao'
      fullPath: '/dao'
      preLoaderRoute: typeof DaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comments': {
      id: '/comments'
      path: '/comments'
      fullPath: '/comments'
      preLoaderRoute: typeof CommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rpc/$': {
      id: '/rpc/$'
      path: '/rpc/$'
      fullPath: '/rpc/$'
      preLoaderRoute: typeof RpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$id': {
      id: '/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof PostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dukigen/$agentId': {
      id: '/dukigen/$agentId'
      path: '/$agentId'
      fullPath: '/dukigen/$agentId'
      preLoaderRoute: typeof DukigenAgentIdRouteImport
      parentRoute: typeof DukigenRoute
    }
    '/api/sync-events': {
      id: '/api/sync-events'
      path: '/api/sync-events'
      fullPath: '/api/sync-events'
      preLoaderRoute: typeof ApiSyncEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seed': {
      id: '/api/seed'
      path: '/api/seed'
      fullPath: '/api/seed'
      preLoaderRoute: typeof ApiSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notify-txs': {
      id: '/api/notify-txs'
      path: '/api/notify-txs'
      fullPath: '/api/notify-txs'
      preLoaderRoute: typeof ApiNotifyTxsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/check-name': {
      id: '/api/users/check-name'
      path: '/api/users/check-name'
      fullPath: '/api/users/check-name'
      preLoaderRoute: typeof ApiUsersCheckNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/sync-events': {
      id: '/api/debug/sync-events'
      path: '/api/debug/sync-events'
      fullPath: '/api/debug/sync-events'
      preLoaderRoute: typeof ApiDebugSyncEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/refresh': {
      id: '/api/auth/refresh'
      path: '/api/auth/refresh'
      fullPath: '/api/auth/refresh'
      preLoaderRoute: typeof ApiAuthRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/nonce': {
      id: '/api/auth/nonce'
      path: '/api/auth/nonce'
      fullPath: '/api/auth/nonce'
      preLoaderRoute: typeof ApiAuthNonceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/debug-login/$': {
      id: '/api/auth/debug-login/$'
      path: '/api/auth/debug-login/$'
      fullPath: '/api/auth/debug-login/$'
      preLoaderRoute: typeof ApiAuthDebugLoginSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DukigenRouteChildren {
  DukigenAgentIdRoute: typeof DukigenAgentIdRoute
}

const DukigenRouteChildren: DukigenRouteChildren = {
  DukigenAgentIdRoute: DukigenAgentIdRoute,
}

const DukigenRouteWithChildren =
  DukigenRoute._addFileChildren(DukigenRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommentsRoute: CommentsRoute,
  DaoRoute: DaoRoute,
  DukigenRoute: DukigenRouteWithChildren,
  FavoritesRoute: FavoritesRoute,
  FormatdocRoute: FormatdocRoute,
  JobsRoute: JobsRoute,
  MarketRoute: MarketRoute,
  Market_searchRoute: Market_searchRoute,
  NewestRoute: NewestRoute,
  PastRoute: PastRoute,
  ShowRoute: ShowRoute,
  SubmitRoute: SubmitRoute,
  SubmittedRoute: SubmittedRoute,
  ThreadsRoute: ThreadsRoute,
  UpvotedRoute: UpvotedRoute,
  UserRoute: UserRoute,
  VoiceRoute: VoiceRoute,
  WelcomeRoute: WelcomeRoute,
  ApiNotifyTxsRoute: ApiNotifyTxsRoute,
  ApiSeedRoute: ApiSeedRoute,
  ApiSyncEventsRoute: ApiSyncEventsRoute,
  PostIdRoute: PostIdRoute,
  RpcSplatRoute: RpcSplatRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthNonceRoute: ApiAuthNonceRoute,
  ApiAuthRefreshRoute: ApiAuthRefreshRoute,
  ApiDebugSyncEventsRoute: ApiDebugSyncEventsRoute,
  ApiUsersCheckNameRoute: ApiUsersCheckNameRoute,
  ApiAuthDebugLoginSplatRoute: ApiAuthDebugLoginSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
