// ⚠️ AUTO-GENERATED — do not edit manually
// Run: pnpm run db:codegen
// Source of truth: apps/webapp/migrations/0000_schema.sql

/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Comments {
  ancestor_path: Generated<string>;
  boost_amount: Generated<number | null>;
  created_at: number;
  dead: Generated<number | null>;
  depth: Generated<number>;
  id: Generated<bigint | null>;
  latest_evt_seq: Generated<number>;
  locale: Generated<string>;
  parent_id: bigint | null;
  points: Generated<number | null>;
  post_id: bigint;
  text: string;
  total_boost: Generated<number | null>;
  updated_at: Generated<number>;
  username: string;
}

export interface Events {
  address: string;
  agg_id: Generated<number>;
  agg_type: Generated<number>;
  block_number: Generated<number>;
  created_at: number;
  evt_seq: Generated<number | null>;
  evt_time: number;
  evt_type: number;
  payload: Uint8Array | null;
  user_evt_seq: Generated<number>;
  username: string;
}

export interface Posts {
  boost_amount: Generated<number | null>;
  comment_count: Generated<number | null>;
  created_at: number;
  dead: Generated<number | null>;
  domain: string | null;
  flags: Generated<number | null>;
  id: Generated<bigint | null>;
  kind: string;
  latest_evt_seq: Generated<number | null>;
  locale: Generated<string>;
  points: Generated<number | null>;
  post_data: Uint8Array | null;
  text: string | null;
  text_en: Generated<string | null>;
  title: string;
  title_en: Generated<string | null>;
  total_boost: Generated<number | null>;
  updated_at: number;
  url: string | null;
  url_en: Generated<string | null>;
  username: string;
}

export interface Translations {
  created_at: number;
  locale: string;
  text: string;
  tid: string;
}

export interface UserInteractions {
  bits_flag: Generated<number>;
  created_at: number;
  item_id: bigint;
  item_type: string;
  updated_at: number;
  username: string;
}

export interface Users {
  about: Generated<string | null>;
  address: string;
  created_at: number;
  duki_bps: Generated<number | null>;
  email: Generated<string | null>;
  karma: Generated<number | null>;
  latest_evt_seq: Generated<number | null>;
  updated_at: number;
  username: string;
}

export interface X402TriggeredCmds {
  amount: number;
  created_at: number;
  duki_bps: Generated<number | null>;
  error_msg: string | null;
  evt_type: number;
  payer_address: string;
  payment_tx_hash: string | null;
  post_id: bigint | null;
  status: Generated<string>;
  updated_at: number;
  username: string | null;
}

export interface DB {
  comments: Comments;
  events: Events;
  posts: Posts;
  translations: Translations;
  user_interactions: UserInteractions;
  users: Users;
  x402_triggered_cmds: X402TriggeredCmds;
}
